import * as stylex from "@stylexjs/stylex";

import { lightShadowTokens, lightThemeTokens } from "./tokens.stylex";

export const controlStyles = stylex.create({
  controlSurface: {
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: lightThemeTokens.borderSubtle,
    borderRadius: "18px",
    backgroundColor: lightThemeTokens.surfacePanel,
    boxShadow: lightShadowTokens.panel,
    backdropFilter: "blur(18px)",
  },
  field: {
    display: "grid",
    gap: "10px",
  },
  fieldLabel: {
    margin: 0,
    fontFamily: lightThemeTokens.fontMono,
    fontSize: "11px",
    letterSpacing: "0.22em",
    textTransform: "uppercase",
    color: lightThemeTokens.textKicker,
  },
  selectWrap: {
    position: "relative",
  },
  selectTrigger: {
    width: "100%",
    minHeight: "48px",
    display: "grid",
    gridTemplateColumns: "1fr auto",
    alignItems: "center",
    gap: "12px",
    padding: "0 14px",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: lightThemeTokens.borderSubtle,
    borderRadius: "16px",
    backgroundColor: lightThemeTokens.surfaceOverlay,
    backgroundImage:
      "linear-gradient(180deg, rgba(255, 255, 255, 0.06), rgba(255, 255, 255, 0)), linear-gradient(140deg, rgba(46, 142, 163, 0.06), rgba(213, 108, 37, 0.05))",
    color: lightThemeTokens.textPrimary,
    fontFamily: lightThemeTokens.fontBody,
    fontSize: "15px",
    lineHeight: 1.1,
    boxShadow: lightShadowTokens.select,
    outline: "none",
    cursor: "pointer",
    transitionDuration: "160ms",
    transitionProperty: "border-color, box-shadow, background-color, transform",
    ":hover": {
      backgroundColor: lightThemeTokens.surfaceElevated,
      borderColor: lightThemeTokens.borderSoft,
    },
    ":focus-visible": {
      backgroundColor: lightThemeTokens.surfaceElevated,
      borderColor: lightThemeTokens.accentCyan,
      boxShadow: "0 0 0 1px rgba(46, 142, 163, 0.16), 0 16px 36px rgba(123, 94, 64, 0.16)",
    },
    ":disabled": {
      cursor: "not-allowed",
      opacity: 0.56,
    },
  },
  selectTriggerValue: {
    display: "block",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    textAlign: "left",
  },
  selectTriggerIcon: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    color: lightThemeTokens.textKicker,
    pointerEvents: "none",
  },
  selectPopup: {
    minWidth: "var(--anchor-width)",
    maxHeight: "320px",
    overflow: "auto",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: lightThemeTokens.borderSubtle,
    borderRadius: "18px",
    backgroundColor: lightThemeTokens.surfaceElevated,
    backgroundImage:
      "linear-gradient(180deg, rgba(46, 142, 163, 0.08), rgba(46, 142, 163, 0) 22%), linear-gradient(180deg, rgba(255, 255, 255, 0.35), rgba(255, 255, 255, 0))",
    boxShadow: lightShadowTokens.select,
    backdropFilter: "blur(16px)",
    transformOrigin: "var(--transform-origin)",
  },
  selectPopupArrow: {
    fill: lightThemeTokens.surfaceElevated,
    stroke: lightThemeTokens.borderSubtle,
    strokeWidth: "1px",
  },
  selectList: {
    display: "grid",
    gap: "4px",
    padding: "8px",
  },
  selectItem: {
    minHeight: "42px",
    display: "grid",
    gridTemplateColumns: "1fr auto",
    alignItems: "center",
    gap: "10px",
    padding: "0 12px",
    borderRadius: "12px",
    color: lightThemeTokens.textPrimary,
    fontFamily: lightThemeTokens.fontBody,
    fontSize: "14px",
    lineHeight: 1.15,
    cursor: "pointer",
    outline: "none",
    transitionDuration: "140ms",
    transitionProperty: "background-color, color, transform",
    ":hover": {
      backgroundColor: lightThemeTokens.accentCyanSoft,
    },
    ":focus-visible": {
      backgroundColor: lightThemeTokens.accentCyanSoft,
    },
  },
  selectItemIndicator: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    color: lightThemeTokens.accentCyan,
  },
  selectControl: {
    width: "100%",
    minHeight: "48px",
    padding: "0 44px 0 14px",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: lightThemeTokens.borderSubtle,
    borderRadius: "16px",
    backgroundColor: lightThemeTokens.surfaceOverlay,
    backgroundImage:
      "linear-gradient(180deg, rgba(255, 255, 255, 0.06), rgba(255, 255, 255, 0)), linear-gradient(140deg, rgba(46, 142, 163, 0.06), rgba(213, 108, 37, 0.05))",
    color: lightThemeTokens.textPrimary,
    fontFamily: lightThemeTokens.fontBody,
    fontSize: "15px",
    lineHeight: 1.1,
    boxShadow: lightShadowTokens.select,
    appearance: "none",
    cursor: "pointer",
    outline: "none",
    transitionDuration: "160ms",
    transitionProperty: "border-color, box-shadow, background-color, transform",
    ":hover": {
      backgroundColor: lightThemeTokens.surfaceElevated,
      borderColor: lightThemeTokens.borderSoft,
    },
    ":focus-visible": {
      backgroundColor: lightThemeTokens.surfaceElevated,
      borderColor: lightThemeTokens.accentCyan,
      boxShadow: "0 0 0 1px rgba(46, 142, 163, 0.16), 0 16px 36px rgba(123, 94, 64, 0.16)",
    },
  },
  selectArrow: {
    pointerEvents: "none",
    position: "absolute",
    right: "14px",
    top: "50%",
    transform: "translateY(-50%)",
    color: lightThemeTokens.textKicker,
    fontSize: "14px",
    lineHeight: 1,
  },
  legendCard: {
    padding: "18px",
    display: "grid",
    gap: "14px",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: lightThemeTokens.borderSubtle,
    borderRadius: "20px",
    backgroundColor: lightThemeTokens.surfaceOverlayStrong,
    boxShadow: lightShadowTokens.marker,
  },
  legendHeader: {
    display: "grid",
    gap: "4px",
  },
  cardTitle: {
    margin: 0,
    fontSize: "16px",
    lineHeight: 1.15,
    color: lightThemeTokens.textStrong,
  },
  cardBody: {
    margin: 0,
    fontSize: "13px",
    lineHeight: 1.5,
    color: lightThemeTokens.textMuted,
  },
  legendList: {
    display: "grid",
    gap: "8px",
    margin: 0,
    padding: 0,
    listStyle: "none",
  },
  legendItem: {
    display: "grid",
    gridTemplateColumns: "auto 1fr auto",
    alignItems: "center",
    gap: "10px",
    minHeight: "38px",
    padding: "0 10px",
    borderRadius: "14px",
    backgroundColor: lightThemeTokens.surfaceCard,
  },
  legendSwatch: {
    width: "12px",
    height: "12px",
    borderRadius: "999px",
    boxShadow: "0 0 0 1px rgba(255, 255, 255, 0.26)",
  },
  legendDegree: {
    fontSize: "14px",
    color: lightThemeTokens.textStrong,
  },
  legendSolfege: {
    fontFamily: lightThemeTokens.fontMono,
    fontSize: "11px",
    letterSpacing: "0.12em",
    textTransform: "uppercase",
    color: lightThemeTokens.textSubtle,
  },
  summaryCard: {
    padding: "18px",
    display: "grid",
    gap: "14px",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: lightThemeTokens.borderSubtle,
    borderRadius: "20px",
    backgroundColor: lightThemeTokens.surfaceOverlayStrong,
    boxShadow: lightShadowTokens.marker,
  },
  summaryList: {
    display: "grid",
    gap: "8px",
    margin: 0,
    padding: 0,
    listStyle: "none",
  },
  summaryItem: {
    display: "grid",
    gridTemplateColumns: "minmax(0, 1fr) auto",
    alignItems: "center",
    gap: "12px",
    minHeight: "40px",
    padding: "0 10px",
    borderRadius: "14px",
    backgroundColor: lightThemeTokens.surfaceCard,
  },
  summaryTone: {
    display: "grid",
    gap: "2px",
  },
  summaryDegree: {
    fontSize: "14px",
    color: lightThemeTokens.textStrong,
  },
  summarySolfege: {
    fontFamily: lightThemeTokens.fontMono,
    fontSize: "11px",
    letterSpacing: "0.12em",
    textTransform: "uppercase",
    color: lightThemeTokens.textSubtle,
  },
  summaryMeta: {
    fontFamily: lightThemeTokens.fontMono,
    fontSize: "11px",
    letterSpacing: "0.12em",
    textTransform: "uppercase",
    color: lightThemeTokens.textKicker,
  },
});
