import * as stylex from "@stylexjs/stylex";

export const lightThemeTokens = {
  fontBody: '"Space Grotesk", "Trebuchet MS", sans-serif',
  fontMono: '"IBM Plex Mono", monospace',
  textPrimary: "#201811",
  textStrong: "#130e09",
  textMuted: "rgba(57, 44, 31, 0.72)",
  textSoft: "rgba(46, 36, 27, 0.82)",
  textSubtle: "rgba(92, 72, 51, 0.7)",
  textKicker: "rgba(119, 92, 63, 0.78)",
  textInverse: "#fff8f1",
  surfaceCanvas: "#f1e5d5",
  surfacePanel: "rgba(255, 248, 240, 0.88)",
  surfaceOverlay: "rgba(255, 250, 245, 0.94)",
  surfaceOverlayStrong: "rgba(255, 251, 246, 0.98)",
  surfaceElevated: "rgba(255, 250, 244, 0.99)",
  surfaceCard: "rgba(151, 110, 63, 0.08)",
  surfaceMuted: "rgba(139, 101, 57, 0.1)",
  surfaceGhost: "rgba(126, 90, 49, 0.06)",
  borderSubtle: "rgba(148, 106, 59, 0.24)",
  borderSoft: "rgba(148, 106, 59, 0.2)",
  borderFaint: "rgba(148, 106, 59, 0.16)",
  accentCyan: "#2e8ea3",
  accentCyanSoft: "rgba(46, 142, 163, 0.14)",
  accentCyanGlow: "rgba(46, 142, 163, 0.32)",
  accentAmber: "#d56c25",
  accentAmberGlow: "rgba(213, 108, 37, 0.34)",
  accentMagentaGlow: "rgba(166, 87, 52, 0.18)",
  dangerSoft: "#b84731",
  dangerBorder: "rgba(184, 71, 49, 0.24)",
} as const;

export const lightShadowTokens = {
  panel: "0 20px 44px rgba(144, 109, 73, 0.18)",
  node: "0 14px 28px rgba(128, 93, 58, 0.16)",
  nodeCyan: "0 14px 28px rgba(46, 142, 163, 0.14)",
  nodeAmber: "0 14px 28px rgba(213, 108, 37, 0.14)",
  nodeMagenta: "0 14px 28px rgba(166, 87, 52, 0.12)",
  playing: "0 0 0 1px rgba(213, 108, 37, 0.16), 0 16px 32px rgba(213, 108, 37, 0.14)",
  accent: "0 12px 24px rgba(46, 142, 163, 0.16)",
  accentHover: "0 16px 28px rgba(46, 142, 163, 0.18)",
  select: "0 16px 36px rgba(123, 94, 64, 0.16), 0 0 0 1px rgba(46, 142, 163, 0.04)",
  marker: "0 12px 24px rgba(123, 94, 64, 0.12)",
} as const;

export const colorVars = stylex.defineVars({
  textPrimary: stylex.types.color(lightThemeTokens.textPrimary),
  textStrong: stylex.types.color(lightThemeTokens.textStrong),
  textInverse: stylex.types.color(lightThemeTokens.textInverse),
  textMuted: stylex.types.color(lightThemeTokens.textMuted),
  textSoft: stylex.types.color(lightThemeTokens.textSoft),
  textSubtle: stylex.types.color(lightThemeTokens.textSubtle),
  textKicker: stylex.types.color(lightThemeTokens.textKicker),
  surfaceCanvas: stylex.types.color(lightThemeTokens.surfaceCanvas),
  surfacePanel: stylex.types.color(lightThemeTokens.surfacePanel),
  surfaceOverlay: stylex.types.color(lightThemeTokens.surfaceOverlay),
  surfaceOverlayStrong: stylex.types.color(lightThemeTokens.surfaceOverlayStrong),
  surfaceElevated: stylex.types.color(lightThemeTokens.surfaceElevated),
  surfaceCard: stylex.types.color(lightThemeTokens.surfaceCard),
  surfaceMuted: stylex.types.color(lightThemeTokens.surfaceMuted),
  surfaceGhost: stylex.types.color(lightThemeTokens.surfaceGhost),
  borderSubtle: stylex.types.color(lightThemeTokens.borderSubtle),
  borderSoft: stylex.types.color(lightThemeTokens.borderSoft),
  borderFaint: stylex.types.color(lightThemeTokens.borderFaint),
  accentCyan: stylex.types.color(lightThemeTokens.accentCyan),
  accentCyanSoft: stylex.types.color(lightThemeTokens.accentCyanSoft),
  accentCyanGlow: stylex.types.color(lightThemeTokens.accentCyanGlow),
  accentAmber: stylex.types.color(lightThemeTokens.accentAmber),
  accentAmberGlow: stylex.types.color(lightThemeTokens.accentAmberGlow),
  accentMagentaGlow: stylex.types.color(lightThemeTokens.accentMagentaGlow),
  dangerSoft: stylex.types.color(lightThemeTokens.dangerSoft),
  dangerBorder: stylex.types.color(lightThemeTokens.dangerBorder),
});

export const fontVars = stylex.defineVars({
  body: lightThemeTokens.fontBody,
  mono: lightThemeTokens.fontMono,
});

export const shadowVars = stylex.defineVars({
  panel: lightShadowTokens.panel,
  node: lightShadowTokens.node,
  nodeCyan: lightShadowTokens.nodeCyan,
  nodeAmber: lightShadowTokens.nodeAmber,
  nodeMagenta: lightShadowTokens.nodeMagenta,
  playing: lightShadowTokens.playing,
  accent: lightShadowTokens.accent,
  accentHover: lightShadowTokens.accentHover,
  select: lightShadowTokens.select,
  marker: lightShadowTokens.marker,
});

export const lightColorTheme = stylex.createTheme(colorVars, {
  textPrimary: lightThemeTokens.textPrimary,
  textStrong: lightThemeTokens.textStrong,
  textInverse: lightThemeTokens.textInverse,
  textMuted: lightThemeTokens.textMuted,
  textSoft: lightThemeTokens.textSoft,
  textSubtle: lightThemeTokens.textSubtle,
  textKicker: lightThemeTokens.textKicker,
  surfaceCanvas: lightThemeTokens.surfaceCanvas,
  surfacePanel: lightThemeTokens.surfacePanel,
  surfaceOverlay: lightThemeTokens.surfaceOverlay,
  surfaceOverlayStrong: lightThemeTokens.surfaceOverlayStrong,
  surfaceElevated: lightThemeTokens.surfaceElevated,
  surfaceCard: lightThemeTokens.surfaceCard,
  surfaceMuted: lightThemeTokens.surfaceMuted,
  surfaceGhost: lightThemeTokens.surfaceGhost,
  borderSubtle: lightThemeTokens.borderSubtle,
  borderSoft: lightThemeTokens.borderSoft,
  borderFaint: lightThemeTokens.borderFaint,
  accentCyan: lightThemeTokens.accentCyan,
  accentCyanSoft: lightThemeTokens.accentCyanSoft,
  accentCyanGlow: lightThemeTokens.accentCyanGlow,
  accentAmber: lightThemeTokens.accentAmber,
  accentAmberGlow: lightThemeTokens.accentAmberGlow,
  accentMagentaGlow: lightThemeTokens.accentMagentaGlow,
  dangerSoft: lightThemeTokens.dangerSoft,
  dangerBorder: lightThemeTokens.dangerBorder,
} as never);

export const lightFontTheme = stylex.createTheme(fontVars, {
  body: lightThemeTokens.fontBody,
  mono: lightThemeTokens.fontMono,
} as never);

export const lightShadowTheme = stylex.createTheme(shadowVars, {
  panel: lightShadowTokens.panel,
  node: lightShadowTokens.node,
  nodeCyan: lightShadowTokens.nodeCyan,
  nodeAmber: lightShadowTokens.nodeAmber,
  nodeMagenta: lightShadowTokens.nodeMagenta,
  playing: lightShadowTokens.playing,
  accent: lightShadowTokens.accent,
  accentHover: lightShadowTokens.accentHover,
  select: lightShadowTokens.select,
  marker: lightShadowTokens.marker,
} as never);
